In [1]:
import tensorflow as tf

# Gradient Calculation
x = tf.Variable(3.0)
with tf.GradientTape() as tape:
    y = x**2 + 3*x + 2
grad = tape.gradient(y, x)
print("TensorFlow Gradient:", grad.numpy())

# Random Number Generation with Seed
tf.random.set_seed(42)
rand_tf = tf.random.normal(shape=(2, 3))
print("TensorFlow Random:\n", rand_tf.numpy())


TensorFlow Gradient: 9.0
TensorFlow Random:
 [[ 0.3274685 -0.8426258  0.3194337]
 [-1.4075519 -2.3880599 -1.0392479]]


In [2]:
import torch

# Gradient Calculation
x = torch.tensor(3.0, requires_grad=True)
y = x**2 + 3*x + 2
y.backward()
print("PyTorch Gradient:", x.grad.item())

# Random Number Generation with Seed
torch.manual_seed(42)
rand_torch = torch.randn(2, 3)
print("PyTorch Random:\n", rand_torch.numpy())


PyTorch Gradient: 9.0
PyTorch Random:
 [[ 0.33669037  0.1288094   0.23446237]
 [ 0.23033303 -1.1228564  -0.18632829]]


In [ ]:
import jax

# Gradient Calculation
def func(x):
    return x**2 + 3*x + 2
grad_func = jax.grad(func)
print("JAX Gradient:", grad_func(3.0))

# Random Number Generation with Seed
key = jax.random.key(42)
rand_jax = jax.random.normal(key, (2, 3))
print("JAX Random:\n", rand_jax)


JAX Gradient: 9.0
JAX Random:
 [[-0.02830462  0.46713185  0.29570296]
 [ 0.15354592 -0.12403282  0.21692315]]
